version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8001:8001"
    environment:
      - GOOGLE_API_KEY=AIzaSyBvOkBwqLcFdEfGhIjKlMnOpQrStUvWxYz
      - MONGO_URL=mongodb+srv://truthlens:truthlens123@cluster0.mongodb.net/truthlens_db?retryWrites=true&w=majority
      - JWT_SECRET=truthlens-super-secret-jwt-key-2024
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8001
    depends_on:
      - backend
    restart: unless-stopped
